/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	networkendpointgroupv1beta1 "k8s.io/ingress-gce/pkg/apis/networkendpointgroup/v1beta1"
	versioned "k8s.io/ingress-gce/pkg/networkendpointgroup/client/clientset/versioned"
	internalinterfaces "k8s.io/ingress-gce/pkg/networkendpointgroup/client/informers/externalversions/internalinterfaces"
	v1beta1 "k8s.io/ingress-gce/pkg/networkendpointgroup/client/listers/networkendpointgroup/v1beta1"
)

// NetworkEndpointGroupInformer provides access to a shared informer and lister for
// NetworkEndpointGroups.
type NetworkEndpointGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.NetworkEndpointGroupLister
}

type networkEndpointGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNetworkEndpointGroupInformer constructs a new informer for NetworkEndpointGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetworkEndpointGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetworkEndpointGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNetworkEndpointGroupInformer constructs a new informer for NetworkEndpointGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetworkEndpointGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1beta1().NetworkEndpointGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkingV1beta1().NetworkEndpointGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&networkendpointgroupv1beta1.NetworkEndpointGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *networkEndpointGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetworkEndpointGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *networkEndpointGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&networkendpointgroupv1beta1.NetworkEndpointGroup{}, f.defaultInformer)
}

func (f *networkEndpointGroupInformer) Lister() v1beta1.NetworkEndpointGroupLister {
	return v1beta1.NewNetworkEndpointGroupLister(f.Informer().GetIndexer())
}
